### ISSUE TITLE
Installing from repo does not work

### ISSUE THREAD

**Issue by MrGreenTea** [tomzorz/obsidian-link-archive#1]
I've copied the contents from this repo by downloading the source as ZIP (0.1.1 tag) to `.obsidian\plugins\obsidian-link-archive` but I get this error in the console when I try to activate it.

I am on Obsidian version v0.12.15 on Windows

![grafik](https://user-images.githubusercontent.com/9407731/137785860-3ba1cf9c-3ec9-4b71-a868-b2a0601156f0.png)

We will probably need a compiled version as `Obsidian` does not seem to be able to work with typescript directly.

**Comment by zaen323** [comment]
Got the same problem too. Taking a look at other plugins, the ones that have main.ts also have main.js.
I also tried to install this from the community plugin list but could not find it. I'm not familiar with Obsidian's plugin system - does it take a few days to get approved?

**Comment by daxmonson** [comment]
Yes, it does take days to get approval to go in Community plugins.

**Comment by tomzorz** [comment]
Hey folks! Sorry for the issues - I've just updated the repo and the latest release with the correct guide and missing files. Please try again using that - it should have all the necessary files in the release now :)

**Comment by MrGreenTea** [comment]
Thanks @tomzorz 
The repository is still missing the `main.js` file though because you added it to the `.gitignore`.

I can try to add a GitHub action that will build a release zip with the compiled version ready to install if you accept PRs

**Comment by tomzorz** [comment]
Hey @MrGreenTea 

I'm not sure that the repo itself should contain that file, as it's a build output - the main.js is uploaded as a binary attachment to the release here: https://github.com/tomzorz/obsidian-link-archive/releases/tag/0.1.1

The main.js file is ignored by the official plugin template that I based my repo on as well https://github.com/obsidianmd/obsidian-sample-plugin/blob/master/.gitignore#L10
