### ISSUE TITLE
Incorrectly formatting markdown links

### ISSUE THREAD

**Issue by ScottKillen** [tomzorz/obsidian-link-archive#3]
The text `[MyLink](https://mylink.com)` is formatted as `[MyLink](https://mylink.com[(Archived)](https://archive.org/link/))`. Note the mishandling of the final `)`. The Archived link should be placed following the final ')' of the original markdown link.

**Comment by bodhar** [comment]
I've just installed the plugin, but I've tried agianst several notes and I'm not seeing this issue - might be resolved as of v0.2.0.

**Comment by tomzorz** [comment]
Yes, 0.2.0 fixed this!
