### ISSUE TITLE
Bug: Failed to archive

### ISSUE THREAD

**Issue by laurastephsmith** [tomzorz/obsidian-link-archive#7]
I keep getting "1/1 Failed to archive [URL]" followed by "Link archiving done!" But it doesn't do anything. There isn't an error in the console:

[obsidian.md-1647560582064.log](https://github.com/tomzorz/obsidian-link-archive/files/8295283/obsidian.md-1647560582064.log)

```
SYSTEM INFO:
	Obsidian version: v0.13.33
	Installer version: v0.13.31
	Operating system: #1 SMP Debian 5.15.15-1 (2022-01-18) 5.15.0-3-amd64
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Typomagical
	Snippets enabled: 3
	Safe mode: off
	Plugins installed: 40
	Plugins enabled: 2
		1: Divide & Conquer
		2: Link Archive
```

Any ideas? Thanks!

**Comment by tomzorz** [comment]
Nothing based on the logs, but definitely something is borked. Could you share the note, or part of a note where it fails? Maybe there's something weird in the URL

**Comment by laurastephsmith** [comment]
I've tried several notes and URLs, can't find anything that works. But it even fails in a note called "Untitled" with nothing but `https://www.bbc.co.uk/news` in the note. I'm on Linux, for what it's worth. Hmmm...

**Comment by laurastephsmith** [comment]
Well this was an unexpected cause for this bug: my ISP (Vodafone UK) appears to be blocking the Wayback Machine portion of archive.org! I'm fairly sure it used to work, but I haven't used it for ages. I get "unable to connect" if I try to look at anything archived with the Wayback Machine. Closing this issue to go and fight for my freedom...

**Comment by tomzorz** [comment]
Oh dang, thanks for letting me know. Good luck from a fellow Vodafone sufferer!

**Comment by laurastephsmith** [comment]
Haha thanks! I'm actually changing ISPs this month anyway, because they've upped the price (while offering the same plan to new customers at less than I was paying before). I normally use a VPN, but it's on my list of things to troubleshoot at the minute :).
